# Site settings
title: Rodolfo Maciel
email: mail@rodolfomaciel.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rodolfomaciel.com" # the base hostname & protocol for your site
color: '#fff'

timezone: America/Fortaleza
encoding: utf-8

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
exclude: ["README.md"]

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

include: ['_headers', '.htaccess']

collections_dir: collections

collections:
  _posts:
    output: true
    permalink: /:title/
  _drafts:
    output: true
    permalink: /:title/
  lessons:
    output: true
    permalink: /:title